name: preview

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mobile:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v3

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: 👷 Build packages
        run: pnpm run -w build:mobile

      # You can remove this step if you already configured this
      # This project shouldn't be pre-configured with this ID, that's why its omitted
      - name: 👷 Configure project
        working-directory: apps/mobile
        run: |
          eas init --id d202a56f-0162-450d-af3b-a2d2e0678594 --force --non-interactive
          echo $(jq '.expo.runtimeVersion.policy = "sdkVersion"' app.json) > app.json
          
      - name: 🧪 Test eas channels:list
        working-directory: apps/mobile
        run: eas channel:list --json --non-interactive

      - name: 🧪 Test full issue 1752
        working-directory: apps/mobile
        shell: bash
        run: |
          EXPO_DEBUG=true eas channel:list --json --non-interactive > channels.json
          echo `EXPO_DEBUG=true eas channel:list --json --non-interactive > channels.json`
          local channels=`jq '.currentPage[] .name' ./channels.json`
          echo $channels
          echo "Looking for $GITHUB_REF_NAME"
          if printf '%s\0' "${channels[@]}" | grep -Fxqz -- '$GITHUB_REF_NAME'; then
            eas channel:delete --non-interactive $GITHUB_REF_NAME
            eas branch:delete --non-interactive $GITHUB_REF_NAME
          else
            echo "Preview channel not found"
          fi

      - name: 🚀 Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          working-directory: apps/mobile
          command: eas update --auto --branch=pr-${{ github.event.number }}
